Fix opcache preloading
craue/CraueFormFlowBundle pull request #368
Opened 2020-11-21 16:22 UTC by piotrantosik

This PR allows using opcache preloading function
Fix https://github.com/craue/CraueFormFlowBundle/issues/363

2020-11-23 20:38 UTC, craue requested changes
Please also revert the permission change on `FormFlowEvent.php`.

2020-11-23 20:38 UTC, craue commented on Event/FormFlowEventTrait.php
> +}
```suggestion
/**
 * @internal
 * @author Christian Raue <christian.raue@gmail.com>
 * @copyright 2011-2020 Christian Raue
 * @license http://opensource.org/licenses/mit-license.php MIT License
 */
trait FormFlowEventTrait {

	/**
	 * @var FormFlowInterface
	 */
	protected $flow;

	/**
	 * @param FormFlowInterface $flow
	 */
	public function __construct(FormFlowInterface $flow) {
		$this->flow = $flow;
	}

	/**
	 * @return FormFlowInterface
	 */
	public function getFlow() {
		return $this->flow;
	}

}
```

2020-11-23 20:38 UTC, craue commented on composer.json
> +		"doctrine/dbal": "<3.0",
Please revert this change and rebase to current master. I've added support for DBAL 3.

2020-11-24 18:08 UTC, piotrantosik commented
@craue I have made changes, please review again.

2020-11-25 10:07 UTC, merged

2020-11-25 10:07 UTC, craue commented
Thank you, @piotrantosik.